apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: ml-platform
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.14.3
          args:
            - mlflow
            - server
            - --host=0.0.0.0
            - --port=5000
            - --backend-store-uri=sqlite:////mlflow/data/mlflow.db
            - --default-artifact-root=/mlflow/data/artifacts
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - name: data
              mountPath: /mlflow/data
          resources:
            requests:
              cpu: "250m"
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-data
