apiVersion: v1
kind: Namespace
metadata:
  name: zulip
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-training
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-data
